[package]
name = "aes_gcm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "*"
wasm-bindgen = "*"
console_error_panic_hook = "*"
js-sys = "*"

[lib]
crate-type = ["cdylib", "rlib"]